### ISSUE TITLE
Failed to activate the go-playground package

### ISSUE THREAD

**Issue by dale-cooper** [tachiba/atom-go-playground#10]
[Enter steps to reproduce below:]

1. Edit go code
2. Open command palette
3. Type gorun

**Atom Version**: 0.211.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [go-playground](https://github.com/tachiba/atom-go-playground) package, v0.0.2

### Stack Trace

Failed to activate the go-playground package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
  at Object.module.exports.activate (C:\Users\Christian\.atom\packages\go-playground\lib\go-playground.coffee:10:23)
  at Package.module.exports.Package.activateNow (C:\Users\Christian\AppData\Local\atom\app-0.211.0\resources\app.asar\src\package.js:240:19)
  at C:\Users\Christian\AppData\Local\atom\app-0.211.0\resources\app.asar\src\package.js:772:25
  at Emitter.module.exports.Emitter.emit (C:\Users\Christian\AppData\Local\atom\app-0.211.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Christian\AppData\Local\atom\app-0.211.0\resources\app.asar\src\command-registry.js:222:20)
  at C:\Users\Christian\AppData\Local\atom\app-0.211.0\resources\app.asar\src\command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\Christian\AppData\Local\atom\app-0.211.0\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\Christian\AppData\Local\atom\app-0.211.0\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (C:\Users\Christian\AppData\Local\atom\app-0.211.0\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Christian\AppData\Local\atom\app-0.211.0\resources\app.asar\src\command-registry.js:241:29)
  at C:\Users\Christian\AppData\Local\atom\app-0.211.0\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Christian\AppData\Local\atom\app-0.211.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Christian\AppData\Local\atom\app-0.211.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\Christian\AppData\Local\atom\app-0.211.0\resources\app.asar\src\window-event-handler.js:180:20)

```

### Commands

```
     -7:01.8.0 core:move-down (atom-text-editor#editor.fontFamily.editor.mini.is-focused)
     -7:01.5.0 core:move-up (atom-text-editor#editor.fontFamily.editor.mini.is-focused)
     -4:32 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:08.5.0 command-palette:toggle (input.hidden-input)
     -0:03.3.0 core:confirm (input.hidden-input)
     -0:03.3.0 go-playground:execute (input.hidden-input)
```

### Config

```json
{
  "core": {},
  "go-playground": {}
}
```

### Installed Packages

```coffee
# User
go-playground, v0.0.2
go-plus, v3.3.12
minimap, v4.10.0

# Dev
No dev packages
```

**Comment by Fresheyeball** [comment]
+1

**Comment by herrtreas** [comment]
+1

**Comment by rossmcf** [comment]
+1

**Comment by ElvizLai** [comment]
+1

**Comment by depy** [comment]
+1

**Comment by raveenb** [comment]
+1

**Comment by maciejmrowiec** [comment]
+1

**Comment by ben181231** [comment]
+1

**Comment by wangyun122** [comment]
+1

**Comment by 0i** [comment]
+1

**Comment by deepch** [comment]
+1

**Comment by dbmlabs** [comment]
+1

**Comment by aleksandarristic** [comment]
Aaaand +1

**Comment by anthony-cervantes** [comment]
:+1:

**Comment by sbucek** [comment]
+1

**Comment by dinhxuanvu** [comment]
+1

**Comment by Aaron-z** [comment]
+1

**Comment by dynamix** [comment]
+1

**Comment by benjamin-rood** [comment]
+1
Atom 1.2.0
OS X El Capitan 10.11.2 Beta (15C47a)

**Comment by pozgo** [comment]
+1 
Atom 1.2.1
OSX  EL Cap 10.11.1

**Comment by marko-ciric** [comment]
+1

**Comment by bfitzsimmons** [comment]
+1

**Comment by josephbergevin** [comment]
+1

**Comment by westtrade** [comment]
+1

**Comment by miluoZ** [comment]
+1

**Comment by dhilipsiva** [comment]
+1

**Comment by stingelin** [comment]
+1

**Comment by brennebeck** [comment]
@tachiba is this project completely unmaintained? If so, do you have an alternative or should we start looking for people to assist in getting it up to date?

**Comment by pozgo** [comment]
I think forking it and starting a community work on it is a way to go. Anyone interested in developing it?

**Comment by brennebeck** [comment]
I'm not sure how much dev time I can put into it with my current
commitments, but definitely interested in assisting. It would be a shame to
see this project go to waste. I can take a look at the code tomorrow and
get back to you then.

I think it would be best if we could get a few people together to assist in
the effort, rather than just a single person fork and do an org-fork.


Bernd Rennebeck
[image: Facebook]  <https://www.facebook.com/hinmn> [image: Github]
<https://github.com/brennebeck> [image: HackerNews]
<https://news.ycombinator.com/user?id=brennebeck> [image: Twitter]
<https://twitter.com/brennebeck> [image: LinkedIn]
<http://ph.linkedin.com/in/berndrennebeck/>

**Comment by beregueder** [comment]
+1

**Comment by brennebeck** [comment]
@pozgo What do you think? Is it only us that are willing or do you have some others that may be interested?

**Comment by Jake570** [comment]
+1

**Comment by pozgo** [comment]
I'll try to fork it to our space @ million12 and then we could start slowly contribute to this. Let me know if you like the idea. I'm not sure how much time I could put into this project but fingers crossed and maybe we will make it live again :)

**Comment by iketutg** [comment]
+1

**Comment by sudomilk** [comment]
+1

**Comment by josephbergevin** [comment]
FWIW: In SublimeText, I use the `go-sublime` package to create a mock playground. 

1. Open a new tab
2. Set the syntax as `GoSublime: Go` 
3. Paste in your playground code _as-is_

- **To Run:** `GoSublime: Replay current package`
- **To Format:** `GoSublime: Fmt the current file (without saving it)`

**Advantages over running on play.golang.org:**
1. The time package actually works as expected
2. You can import any package that is in your gopath

I wonder if the commands `Replay current package` and `Fmt the current file (without saving it)` could be replicated with this playground package...

**Comment by chespinoza** [comment]
+1

**Comment by nishimao** [comment]
+1

**Comment by autoscatto** [comment]
+1

**Comment by Am6puk** [comment]
+1

**Comment by ajpen** [comment]
+1

**Comment by ejronin** [comment]
+1

**Comment by dmatthe4952** [comment]
+1 linux machine running Atom 1.15.0

**Comment by kinarashah** [comment]
+1

```
Cannot read property 'command' of undefined
Hide Stack Trace
TypeError: Cannot read property 'command' of undefined
    at Object.activate (/Users/kshah/.atom/packages/go-playground/lib/go-playground.coffee:10:23)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:253:25)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:645:40)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:519:35
    at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:17)
    at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:359:17
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:220:15)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

**Comment by miholeus** [comment]
+1

**Comment by wss655366** [comment]
I cat't use it
