### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by GoesToEleven** [tachiba/atom-go-playground#6]
0. install packages: autocomplete-plus, go-plus, go-playground
1. create any go program 
2. command + shift + p
3. gorun

this error comes up:
Uncaught Error: spawn EACCES
child_process.js:1160
Hide Stack TraceShow Stack Trace
Error: spawn EACCES
    at exports._errnoException (util.js:753:11)
    at ChildProcess.spawn (child_process.js:1160:11)
    at Object.exports.spawn (child_process.js:993:9)
    at new BufferedProcess (/Users/tm002/Atom.app/Contents/Resources/app/src/buffered-process.js:51:37)
    at Object.module.exports.execute (/Users/tm002/.atom/packages/go-playground/lib/go-playground.coffee:43:24)
    at atom-workspace.<anonymous> (/Users/tm002/.atom/packages/go-playground/lib/go-playground.coffee:17:24)
    at atom-workspace.handler (/Users/tm002/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
    at atom-workspace.jQuery.event.dispatch (/Users/tm002/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
    at atom-workspace.elemData.handle (/Users/tm002/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/tm002/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
The error was thrown from the go-playground package. You can help by creating an issue. Please explain what actions triggered this error.

**Atom Version**: 0.181.0
**System**: Mac OS X 10.10.2
**Thrown From**: [go-playground](https://github.com/tachiba/atom-go-playground) package, v0.0.2

### Stack Trace

Uncaught Error: spawn EACCES

```
At child_process.js:1160

Error: spawn EACCES
    at exports._errnoException (util.js:753:11)
    at ChildProcess.spawn (child_process.js:1160:11)
    at Object.exports.spawn (child_process.js:993:9)
    at new BufferedProcess (/Users/tm002/Atom.app/Contents/Resources/app/src/buffered-process.js:51:37)
    at Object.module.exports.execute (/Users/tm002/.atom/packages/go-playground/lib/go-playground.coffee:43:24)
    at atom-workspace.<anonymous> (/Users/tm002/.atom/packages/go-playground/lib/go-playground.coffee:17:24)
    at atom-workspace.handler (/Users/tm002/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
    at atom-workspace.jQuery.event.dispatch (/Users/tm002/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
    at atom-workspace.elemData.handle (/Users/tm002/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/tm002/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
```

### Commands

```
     -0:02.3 core:save (atom-text-editor.editor.is-focused)
     -0:01.4 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:00.5 core:confirm (atom-text-editor.editor.mini)
     -0:00.5 go-playground:execute (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "go-playground": {
    "go_executable_path": "/usr/local/go/bin"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.1.6
go-playground, v0.0.2
go-plus, v3.2.2

# Dev
No dev packages
```

**Comment by vitalybaev** [comment]
+1, the same issue
